language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
  - "0.10"
branches:
  only:
    - master
before_install:
  - git config --global push.default matching
  - git config --global user.name "erguotou"
  - git config --global user.email "erguotou525@gmail.com"
install:
  - npm install
script:
  - npm run test
cache:
  directories:
    - node_modules